name: kdemos_mobile
description: "Professional mobile application for Kdemos calendar scheduling platform. Built with Flutter for iOS and Android deployment to App Store and Play Store."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies for professional app
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  webview_flutter: ^4.4.2
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  url_launcher: ^6.2.1
  permission_handler: ^11.1.0
  
  # UI and Navigation
  go_router: ^12.1.3
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Utilities
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  # fonts:
  #   - family: InterTight
  #     fonts:
  #       - asset: assets/fonts/InterTight-Regular.ttf
  #       - asset: assets/fonts/InterTight-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/InterTight-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/InterTight-Bold.ttf
  #         weight: 700

# App launcher icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#007AFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Splash screen configuration
flutter_native_splash:
  color: "#FAFAFA"
  image: "assets/images/splash_logo.png"
  color_dark: "#121212"
  image_dark: "assets/images/splash_logo_dark.png"
  android_12:
    image: "assets/images/splash_logo.png"
    color: "#FAFAFA"
    image_dark: "assets/images/splash_logo_dark.png"
    color_dark: "#121212"